### ISSUE TITLE
Add ability to consume xyz.listen.overdrive.com links

### ISSUE THREAD

**Issue by banagale** [davideg/overdrive-dl#2]
Thank you for your work on this tool.

The overdrive media app doesn't work on 64-bit versions of macOS. Overdrive Support says they have no plans to update that app at this time.

Is there a way to get .odm files without it or perhaps parse similar data from the browser-based version?

It would be great if this tool could consume overdrive web endpoints.

The url for audiobooks is formed like:

```
https://ofs-[some_string].listen.overdrive.com/?d=[some_key_string]
```

The source includes content like:

```
The "nav":{"toc":[{"title":"Fear: Trump in the White House",
"path":"{[some_path_key_thing]}Fmt425-Part01.mp3"},
{"title":"Epigraph","path":"{C20A6551-C8FD-4DB2-8F8B-37B0CD238654}Fmt425-Part01.mp3#30"},{"title":"Note to Readers","path":"{C20A6551-C8FD-4DB2-8F8B-37B0CD238654}Fmt425-Part01.mp3#51"},{"title":"Prologue","path":"{C20A6551-C8FD-4DB2-8F8B-37B0CD238654}Fmt425-Part01.mp3#98"},
{"title":"Chapter 1","path":"{[some_path_key_thing]}Fmt425-Part01.mp3#855"}
```

Not sure if this is similar to odm but if so, would be a nice get.

**Comment by davideg** [comment]
Hi @banagale! Sorry it's taken me forever to respond to you. I don't regularly check my GitHub notifications 😜. Oops!

I usually go on my library's OverDrive website and navigate to the Loans page (e.g. `https://<library>.overdrive.com/<library>/content/account/loans`) and click "Download MP3 audiobook". It warns me that the OverDrive app is required but I end up with a .odm file that I use with this tool.

![image](https://user-images.githubusercontent.com/395397/114503856-c7af4a00-9be2-11eb-92ff-7ecbc9b4a908.png)

Do you only have the option to listen in the browser? I see the page you're talking about and it looks like it uses a different method for streaming the audiobook.

**Comment by banagale** [comment]
No problem. Thanks for the reply. I’ll check on that method.

**Comment by davideg** [comment]
@banagale you might be interested in checking out https://github.com/lullius/pylibby

When odm is fully phased out, hopefully this tool will still work 🙏
